# Generated by Django 4.0.4 on 2022-06-18 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_sender', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='telegram_id',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
