# Generated by Django 4.0.4 on 2022-06-08 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_sender', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='is_sended',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='categories',
            field=models.ManyToManyField(related_name='user', to='book_sender.category', verbose_name='Categories'),
        ),
        migrations.DeleteModel(
            name='UsersBooks',
        ),
    ]
