# Generated by Django 4.0.4 on 2022-06-08 21:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('book_sender', '0002_book_is_sended_user_categories_delete_usersbooks'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('email', models.EmailField(max_length=254, primary_key=True, serialize=False, verbose_name='Email')),
                ('telegram_login', models.CharField(blank=True, max_length=255)),
                ('categories', models.ManyToManyField(blank=True, related_name='client', to='book_sender.category', verbose_name='Categories')),
            ],
        ),
        migrations.CreateModel(
            name='Token',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expiration_time', models.DateTimeField()),
                ('value', models.CharField(max_length=255)),
                ('client_email', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='book_sender.client')),
            ],
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
